package chains

import "github.com/Maszz/go-bitkub-sdk/types"

const (
	ERC20  types.BlockChainNetwork = "ETH"
	BEP20  types.BlockChainNetwork = "BSC"
	KAP20  types.BlockChainNetwork = "BKC"
	BTC    types.BlockChainNetwork = "BTC"
	IOST   types.BlockChainNetwork = "IOST"
	CTXCTX types.BlockChainNetwork = "CTXCTX"
	ADA    types.BlockChainNetwork = "ADA"
	DOGE   types.BlockChainNetwork = "DOGE"
	BAND   types.BlockChainNetwork = "BAND"
	SOL    types.BlockChainNetwork = "SOL"
	FTM    types.BlockChainNetwork = "FTM"
	LUNC   types.BlockChainNetwork = "LUNA"
	XTZ    types.BlockChainNetwork = "XTZ"
	XRP    types.BlockChainNetwork = "XRP"
	OP     types.BlockChainNetwork = "OP"
	BCH    types.BlockChainNetwork = "BCH"
	SCRT   types.BlockChainNetwork = "SCRT"
	KSM    types.BlockChainNetwork = "KSM"
	TRX    types.BlockChainNetwork = "TRX"
	XLM    types.BlockChainNetwork = "XLM"
	ZIL    types.BlockChainNetwork = "ZIL"
	DOT    types.BlockChainNetwork = "DOT"
	SGB    types.BlockChainNetwork = "SGB"
	MATIC  types.BlockChainNetwork = "MATIC"
	HBAR   types.BlockChainNetwork = "HBAR"
	CELO   types.BlockChainNetwork = "CELO"
	ALGO   types.BlockChainNetwork = "ALGO"
	LUNA   types.BlockChainNetwork = "LUNA2"
	NEAR   types.BlockChainNetwork = "NEAR"
	WAN    types.BlockChainNetwork = "WAN"
	AVAX_C types.BlockChainNetwork = "AVAX_C"
	ATOM   types.BlockChainNetwork = "ATOM"
	FLOW   types.BlockChainNetwork = "FLOW"
	FLR    types.BlockChainNetwork = "FLR"
	ARB    types.BlockChainNetwork = "ARB"
)
