package symbols

import (
	"github.com/Maszz/go-bitkub-sdk/types"
)

const (
	/*
		Auto generated from https://api.bitkub.com/api/market/types.symbols @ 7 may 2023
	*/
	THB_BTC   types.Symbol = "THB_BTC"
	THB_ETH   types.Symbol = "THB_ETH"
	THB_WAN   types.Symbol = "THB_WAN"
	THB_ADA   types.Symbol = "THB_ADA"
	THB_OMG   types.Symbol = "THB_OMG"
	THB_BCH   types.Symbol = "THB_BCH"
	THB_USDT  types.Symbol = "THB_USDT"
	THB_XRP   types.Symbol = "THB_XRP"
	THB_ZIL   types.Symbol = "THB_ZIL"
	THB_SNT   types.Symbol = "THB_SNT"
	THB_CVC   types.Symbol = "THB_CVC"
	THB_LINK  types.Symbol = "THB_LINK"
	THB_IOST  types.Symbol = "THB_IOST"
	THB_ZRX   types.Symbol = "THB_ZRX"
	THB_KNC   types.Symbol = "THB_KNC"
	THB_ABT   types.Symbol = "THB_ABT"
	THB_MANA  types.Symbol = "THB_MANA"
	THB_CTXC  types.Symbol = "THB_CTXC"
	THB_XLM   types.Symbol = "THB_XLM"
	THB_SIX   types.Symbol = "THB_SIX"
	THB_JFIN  types.Symbol = "THB_JFIN"
	THB_BNB   types.Symbol = "THB_BNB"
	THB_POW   types.Symbol = "THB_POW"
	THB_DOGE  types.Symbol = "THB_DOGE"
	THB_TRX   types.Symbol = "THB_TRX"
	THB_DAI   types.Symbol = "THB_DAI"
	THB_XTZ   types.Symbol = "THB_XTZ"
	THB_ALGO  types.Symbol = "THB_ALGO"
	THB_USDC  types.Symbol = "THB_USDC"
	THB_BUSD  types.Symbol = "THB_BUSD"
	THB_BAT   types.Symbol = "THB_BAT"
	THB_MKR   types.Symbol = "THB_MKR"
	THB_ENJ   types.Symbol = "THB_ENJ"
	THB_BAND  types.Symbol = "THB_BAND"
	THB_COMP  types.Symbol = "THB_COMP"
	THB_KSM   types.Symbol = "THB_KSM"
	THB_DOT   types.Symbol = "THB_DOT"
	THB_NEAR  types.Symbol = "THB_NEAR"
	THB_SCRT  types.Symbol = "THB_SCRT"
	THB_GLM   types.Symbol = "THB_GLM"
	THB_DON   types.Symbol = "THB_DON"
	THB_YFI   types.Symbol = "THB_YFI"
	THB_UNI   types.Symbol = "THB_UNI"
	THB_AAVE  types.Symbol = "THB_AAVE"
	THB_ALPHA types.Symbol = "THB_ALPHA"
	THB_OCEAN types.Symbol = "THB_OCEAN"
	THB_SNX   types.Symbol = "THB_SNX"
	THB_SAND  types.Symbol = "THB_SAND"
	THB_BAL   types.Symbol = "THB_BAL"
	THB_CRV   types.Symbol = "THB_CRV"
	THB_GRT   types.Symbol = "THB_GRT"
	THB_MATIC types.Symbol = "THB_MATIC"
	THB_KUB   types.Symbol = "THB_KUB"
	THB_AXS   types.Symbol = "THB_AXS"
	THB_SUSHI types.Symbol = "THB_SUSHI"
	THB_IMX   types.Symbol = "THB_IMX"
	THB_DYDX  types.Symbol = "THB_DYDX"
	THB_ENS   types.Symbol = "THB_ENS"
	THB_BOBA  types.Symbol = "THB_BOBA"
	THB_ILV   types.Symbol = "THB_ILV"
	THB_GALA  types.Symbol = "THB_GALA"
	THB_GT    types.Symbol = "THB_GT"
	THB_SGB   types.Symbol = "THB_SGB"
	THB_LYXE  types.Symbol = "THB_LYXE"
	THB_CHZ   types.Symbol = "THB_CHZ"
	THB_GF    types.Symbol = "THB_GF"
	THB_EXFI  types.Symbol = "THB_EXFI"
	THB_SOL   types.Symbol = "THB_SOL"
	THB_AVAX  types.Symbol = "THB_AVAX"
	THB_FTM   types.Symbol = "THB_FTM"
	THB_LUNA  types.Symbol = "THB_LUNA"
	THB_APE   types.Symbol = "THB_APE"
	THB_HBAR  types.Symbol = "THB_HBAR"
	THB_LRC   types.Symbol = "THB_LRC"
	THB_CELO  types.Symbol = "THB_CELO"
	THB_GAL   types.Symbol = "THB_GAL"
	THB_SOLO  types.Symbol = "THB_SOLO"
	THB_LUNA2 types.Symbol = "THB_LUNA2"
	THB_OP    types.Symbol = "THB_OP"
	THB_1INCH types.Symbol = "THB_1INCH"
	THB_ATOM  types.Symbol = "THB_ATOM"
	THB_LDO   types.Symbol = "THB_LDO"
	THB_STG   types.Symbol = "THB_STG"
	THB_AXL   types.Symbol = "THB_AXL"
	THB_FLOW  types.Symbol = "THB_FLOW"
	THB_FLR   types.Symbol = "THB_FLR"
	THB_FXS   types.Symbol = "THB_FXS"
	THB_HFT   types.Symbol = "THB_HFT"
	THB_ARB   types.Symbol = "THB_ARB"
)
